### PR TITLE
Add schema annotations to javadoc

### PR DESCRIPTION
**Pull request by at055612**
The xmlschema I work on has been heavily documented with `xs:annotation/xs:documentation` elements. I wanted to be able to pull this documentation through into the javadoc of the generated classes and their Builders.

This PR adds a new argument to the fluent-builder plugin `generateJavadocFromAnnotations` which defaults to false.  If set to true it will add schema annotations to the class getters/setters and the builder with.../add... methods.  Class level javadoc from schema annotations is already handled by _xjc_.  The annotation text is also hard wrapped to 80chars to improve the appearance when viewing the raw source.

For a better explanation see the generated README.

I also added `com.kscs.util.test.GenerateClasses` with a main method for running xjc from java to help with debugging the plugin.

Unfortunately my long forgotten school level German doesn't extend to providing the `_de` translations.

### CODE REVIEW

**Comment by at055612** [comment]
I have just found a bug with this when used with xs:choice items.  I will investigate.

**Comment by at055612** [comment]
The problems with xs:choice are now fixed.
4bf5de0 fixes a bug that exists on master.
I think the PR is ready for review and merge.

**Comment by at055612** [comment]
If I try and run 
``` bash
cd test-module
mvn clean install
```
I get errors with the xhtml5.xsd along the lines of
```
[ERROR] Error while generating code.Location [ file:/home/dev/git_work/jaxb2-rich-contract-plugin/test-module/src/main/resources/xhtml5.xsd{497,31}].                                                        
org.xml.sax.SAXParseException: A class/interface with the same name "org.w3._1999.xhtml.Li" is already in use. Use a class customization to resolve this conflict.                                           
    at com.sun.tools.xjc.util.CodeModelClassFactory.createClass (CodeModelClassFactory.java:121)                                                                                                             
    at com.sun.tools.xjc.util.CodeModelClassFactory.createClass (CodeModelClassFactory.java:82)                                                                                                              
    at com.sun.tools.xjc.generator.bean.ImplStructureStrategy$1.createClasses (ImplStructureStrategy.java:82)
```

To get the test-module to build on this branch I have had to un-comment the block at line 72 of `test-module/pom.xml`.  It looks like this pom will also not build on `master`.

**Comment by at055612** [comment]
I would really appreciate it if you could review this PR and if you are happy with the changes, merge to master and release to maven central.  I have a repo that needs the changes in this PR.  I would much rather use your plugin than have to fork your repo and release that fork.

If there is anything in this PR that needs changing then please let me know and I will change it.

**Comment by mklemm** [comment]
OK, pull request has been merged. MNo public release yet, but will come.

**Comment by at055612** [comment]
Thanks for merging. Much appreciated.

**Comment by at055612** [comment]
Is there any chance you could make a release with the merged code or let me know when you think you will be able to?

**Pull request merged**
